# Use root/example as user/password credentials
version: '3.1'

services:
  ticker-beats-admin:
    image: gcr.io/ticker-beats/ticker-beats-admin:latest
    container_name: ticker-beats-admin
    restart: unless-stopped
    env_file: ticker-beats-prod.env
    ports:
      - 31034:31034
    networks:
      - ticker-beats-ntw

networks:
  ticker-beats-ntw:
    driver: bridge

volumes:
  ticker-beats-vol:
    driver: local